project_id = "mavbnybtyfewfsihmuri"

[functions.send-task-notification]
verify_jwt = false

[functions.send-event-notification]
verify_jwt = false

[functions.create-bulk-users]
verify_jwt = false

[functions.marketing-dispatch-campaign]
verify_jwt = false

[functions.send-waitlist-confirmation]
verify_jwt = false