// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://mavbnybtyfewfsihmuri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hdmJueWJ0eWZld2ZzaWhtdXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTAxNjQsImV4cCI6MjA2OTQ4NjE2NH0.mNwiahlLZKccFDfqzy0tzr1Y2sAnxf-OF-L2T2Hvh88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    // Email links, magic links, and OAuth return tokens in the URL; this reduces failed sessions after redirect.
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});